export default function Home() {
  return (
    <div>헬로!
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
      <div>깔깔깔깔</div>
    </div>
  )
}
